defaultProfile: ca32_endv
configuration:
    type: endevor
    schema:
        type: object
        title: 'The CA Endevor SCM endevor profile'
        description: 'The CA Endevor SCM endevor profile schema, where you specify your endevor session information and credentials'
        properties:
            host:
                optionDefinition:
                    description: 'The hostname of the endevor session'
                    type: string
                    name: host
                    aliases:
                        - hostname
                type: string
            port:
                optionDefinition:
                    description: 'The port number of the endevor session'
                    type: number
                    name: port
                    aliases:
                        - p
                type: number
            user:
                optionDefinition:
                    description: 'The username of the endevor session'
                    type: string
                    name: user
                    aliases:
                        - username
                secure: true
                type: string
            password:
                optionDefinition:
                    description: 'The password of the user'
                    type: string
                    name: password
                    aliases:
                        - pass
                secure: true
                type: string
            protocol:
                optionDefinition:
                    description: 'The protocol used for connecting to CA Endevor SCM Rest API'
                    type: string
                    name: protocol
                    aliases:
                        - prot
                    defaultValue: http
                    allowableValues:
                        values:
                            - http
                            - https
                        caseSensitive: false
                type: string
            basePath:
                optionDefinition:
                    description: 'The base path used for connecting to CA Endevor SCM Rest API'
                    type: string
                    name: base-path
                    aliases:
                        - bp
                    defaultValue: EndevorService/api/v2
                type: string
            rejectUnauthorized:
                optionDefinition:
                    description: 'If set, the server certificate is verified against the list of supplied CAs'
                    type: boolean
                    name: reject-unauthorized
                    aliases:
                        - ru
                type: boolean
    validationPlanModule: 'C:\Users\ej608771\.zowe\plugins\installed\node_modules\@broadcom\endevor-for-zowe-cli\lib\cli\profiles/EndevorProfileValidationPlan'
    createProfileExamples:
        -
            options: 'ndvrSample --host ndvr123 --port 8080 --user ibmuser --password myp4ss --prot http --base-path  EndevorService/api/v2 --reject-unauthorized false'
            description: 'Create an endevor profile called ''ndvrSample'' to connect to CA Endevor SCM web services at host ndvr123 and port 8080,using http protocol, with / EndevorService/api/v2 base path, allowing self-signed certificates'
